### ISSUE TITLE
KeyError: 'Chord_ukn4' 

### ISSUE THREAD

**Issue by VDT5702** [Natooz/MidiTok#77]
I am trying to use a basic code snippet to convert a midi file into tokens, but I keep getting the above-mentioned key error. I have attached the code I am using for reference:

config = TokenizerConfig(nb_velocities=16, use_chords=True, use_programs=True) 
tokenizer = REMI(config)`
midi = MidiFile('Optimus-VIRTUOSO-RGA-Edition-Main-Sample.mid')
tokens = tokenizer(midi)  # calling the tokenizer will automatically detect MIDIs, paths and tokens
converted_back_midi = tokenizer(tokens)

This issue has been persistent with almost all the MIDI files that I have tried to tokenise. I seem to be missing something too trivial.

**Comment by Natooz** [comment]
Hi,
This might be a bug on MidiTok's side.
Could you share here the MIDI file raising the error ?

**Comment by Chunyuan-Li** [comment]
You can try adding chord_unknown=(3,6) in the TokenizerConfig.
(only chords consisting of 3 to 5 notes are considered.)

**Comment by Natooz** [comment]
I finally got some time to look into it. This was indeed a bug in `miditok.utils.detect_chords`.
If `config.chord_unknown` is not set (None), then the `miditok.utils.detect_chords` method shouldn't return unknown chords, which it did anyway.
This is fixed in #84, thank you for the bug report 🙌

**Comment by Natooz** [comment]
Hi 👋,
The fix will feature in the next release (v2.1.7) that should come soon.
You can get it by installing miditok from git: `pip install git+https://github.com/Natooz/MidiTok/`

**Comment by Iceglitter632** [comment]
Hi,

I think I'm on the latest version of miditok but I still get this error when tokenizing some midi files.
This is my code
`midi_tokenizer.tokenize_midi_dataset(midi_paths, tokens_path)`
The error shows `KeyError: 'TimeSig_1/8`. 
I'm using REMIPlus as my tokenizer.
The same error also occurs when using the Dataloader `midi_dataset = DatasetTok(midi_files, min_seq_len=256, max_seq_len=256, tokenizer=midi_tokenizer)`. I read the comments above but I don't really know what to do, can somebody help me please.

Thank you

**Comment by Natooz** [comment]
Hi,
Thank you for the report!
Would you be able to share here the MIDI files causing the issue?
And is it with the same configuration as in your first post?

**Comment by Iceglitter632** [comment]
Hi,
Thank you for the fast reply.
The midi files are from [Zenodo](https://zenodo.org/records/5142664). Due to their policy I cannot share them.
The configuration is the same with the notebook_files inside your github.
```
TOKENIZER_PARAMS = {
    "pitch_range": (21, 109),
    "beat_res": {(0, 4): 8, (4, 12): 4},
    "num_velocities": 32,
    "special_tokens": ["PAD", "BOS", "EOS", "MASK"],
    "use_chords": True,
    "use_rests": False,
    "use_tempos": True,
    "use_time_signatures": False,
    "use_programs": False,
    "num_tempos": 32,  # number of tempo bins
    "tempo_range": (40, 250),  # (min, max)
    
}
config = TokenizerConfig(**TOKENIZER_PARAMS)
```

Thanks once again

**Comment by Natooz** [comment]
Thank you for the details.
I have the dataset, if you can share the paths/names of the MIDIs I would be able to debug more quickly, otherwise I'll just iterate over ;)

I'll look into this after merging #124 which is a big chunk of work of the upcoming next version (v3).

**Comment by Iceglitter632** [comment]
I'll try to find which file is causing the problem. 
Also while trying, I found that there is another key error: `KeyError: 'Position_49'`. 
I think this is not a bug but a configuration I did not set properly.

**Comment by Natooz** [comment]
Noted!
For the Position error, I think this is due to a time signature enforcing a ticks/beat ratio not covered by the tokenizer.
Again, I'll run tests on this, but this should be fixed in #124

**Comment by Natooz** [comment]
Hi 👋

I ran some tests in #124 over the MMD dataset. This PR actually follows the ongoing switch from the miditoolkit backend to [symusic](https://github.com/Yikai-Liao/symusic), which will allow much faster tokenizations. With it came a redesign of the MIDI preprocessing step and of how time values are handled.
Testing over MMD allowed to spot some "edge cases" causing bugs, which are now fixed. I'll release the update soon, you can already benefit from this by installing miditok from git: `pip install git+https://github.com/Natooz/MidiTok`

**Comment by Iceglitter632** [comment]
Thank you for your work. I think its a problem with REMIPlus, after I changed the tokenizer to REMI, it seemed to work fine. I still have some issues with loading the Zenedo data to the DatasetTok, but I should be able to solve it. Thanks once again
